services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    networks:
      - network

  laravel:
    image: php:8.2-fpm
    container_name: laravel
    volumes:
      - ./laravel:/var/www/html
      - storage:/var/www/html/storage
    working_dir: /var/www/html
    environment:
      - APP_ENV=${APP_ENV}
      - DB_HOST=${MYSQL_HOST}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - laravel
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  database:
    driver: local
  storage:
    driver: local
